server:
  port: 8761
spring:
  application:
    name: discovery-ws
  boot:
    admin:
      client:
        url:
        - http://localhost:9999
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true    
