server:
  port: 0
spring:
  application:
    name: generator-service-ws
  devtools:
    restart:
      enabled: true
  boot:
    admin:
      client:
        url:
        - http://localhost:9999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'